### ISSUE TITLE
Provide domains also for reverse addresses according to routing data

### ISSUE THREAD

**Issue by pemensik** [InfrastructureServices/dnsconfd#15]
NM dns plugin for *dnsmasq* does a smart thing, it configures also reverse addresses mapping to IP ranges used on the interface. That way not only forward name to address, but also reverse address to name queries are directed to the interface-specific DNS servers. That would work nice when those addresses are from private ranges, which public internet simply does not know.

Implementation on NM side is at [get_ip_rdns_domains](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/1.44.2/src/core/dns/nm-dns-manager.c?ref_type=tags#L1413).

Exact implementations are at: [nm_utils_get_reverse_dns_domains_ip_4](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/1.44.2/src/core/nm-core-utils.c?ref_type=tags#L4154), [nm_utils_get_reverse_dns_domains_ip_6](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/1.44.2/src/core/nm-core-utils.c?ref_type=tags#L4202).
For a nicer and more compact displaying to users, we may want still to display just IP ranges with prefixes.

**Comment by pemensik** [comment]
Because NM should create a new plugin sending us updates via our own methods, we made some proposals to have IP ranges sent to us already. ServerDescription contains networks list since 1.5 release. Commit f47877475e7f616f39bd32b1d25f70394c7be092.

**Comment by pemensik** [comment]
@TomasKorbar is this issue considered implemented already or not yet?

**Comment by TomasKorbar** [comment]
@pemensik Implemented in 1.5.0.
